### ISSUE TITLE
Some key combo does not work on some applications

### ISSUE THREAD

**Issue by user202729** [nimble0/dotterel#14]
Key combinations:

* `{#Shift_L(Left)}` (considered a `{#Left}`, should select the character on the left) -- in most applications.
* `{#Control_L(u)}` (considered a `{#u}`) -- only in TeamViewer in remote computer mode.

Hacker's keyboard can send all of these combinations without any problem (and have the expected effect).

Perhaps this is caused by something that the application cannot handle too fast keys sent properly?

**Comment by user202729** [comment]
Looking at the source code, I observe that:

* The time stamp for the key down and the key up event are identical.
* There's no key event sent on modifier key down/up (only the modifier mask changes)

**Comment by nimble0** [comment]
Looks like adding key events for the modifier keys fixes it for `{#Shift_L(Left)}`.

**Comment by user202729** [comment]
Nice (I hope there's a new release soon...)

**Comment by user202729** [comment]
Can you push the modified code somewhere? (if you don't want to make a new release immediately...)

**Comment by nimble0** [comment]
Sure. https://github.com/nimble0/dotterel/tree/various-fixes

**Comment by user202729** [comment]
The mentioned patch fixes the TeamViewer issue too.

**Comment by nimble0** [comment]
Excellent, thanks for the report.

**Comment by Zireael07** [comment]
Were the fixes integrated?

**Comment by nimble0** [comment]
Yes, [v0.3.1](https://github.com/nimble0/dotterel/releases/tag/v0.3.1-dev-signed) includes those fixes.
