### ISSUE TITLE
Add more space for dictionary name display

### ISSUE THREAD

**Issue by nsmarkop** [nimble0/dotterel#2]
I tried adding some dictionaries I have on my phone that are in the default storage location + two folders deep into that (".../Sync/Plover/"), but once I've added two I can't tell which one is which because the names are too long and the rows don't expand / scroll to be able to see them:

![screenshot_20180405-201914](https://user-images.githubusercontent.com/4577561/38399230-ad7d72fe-390e-11e8-9e36-9ebab29eb154.png)

**Comment by nimble0** [comment]
Fixed in 231c96a66aa999779c7cd909f1694eb4568e3526
