### ISSUE TITLE
Undo bug when undoing newlines

### ISSUE THREAD

**Issue by Codebreakerblue** [nimble0/dotterel#23]
Pressing * key to undo after pressing R-R, R*R, or SKW-BGS deletes all newlines, punctuation, and the previous word. Changing dictionary definition for R-R to "{^\n^}" functions as normal but has no effect on the undo bug.

**Comment by Codebreakerblue** [comment]
Workaround: deleting the newline using the PW-FP backspace stroke appears to work as expected.

**Comment by nimble0** [comment]
This is not unexpected behaviour for `#Return` translations.

I am unable to reproduce this with `{^\n^}`. Could you provide:
- Dotterel version
- Editor app and version
- Specific steps to reproduce it with output. Video/screenshots would help here.

**Comment by Codebreakerblue** [comment]
I must have been doing something wrong in the json file. It's now mysteriously fixed. I guess I escaped the backslash unnecessarily? 
Here's the info in case it's useful.
Dotterel version 0.4.0, Samsung memo app V1.2.9018997
Json file definition that started working: "R-R": "{^\n^}"
Sorry for the trouble.
