### ISSUE TITLE
Very low accuracy on Monkeytype when using Dotterel

### ISSUE THREAD

**Issue by MarkoSchuetz** [nimble0/dotterel#27]
I have entered an issue over at Monkeytype [#3690](https://github.com/monkeytypegame/monkeytype/issues/3690#issue-1426000775). Then it occurred to me that to solve this the insights of the Dotterel developers would most likely be very helpful: so I'm adding this here.

**Comment by nimble0** [comment]
Fixed in Monkeytype.
