### ISSUE TITLE
Resetting dictionaries does not clear the selection

### ISSUE THREAD

**Issue by nsmarkop** [nimble0/dotterel#3]
If you have an additional dictionary that you added selected and then you press the "reset" button, the additional dictionaries will be cleared from the view but the header will still say that you have one dictionary selected. Selecting the default dictionaries increments the number at this point until you press the back arrow to return things to normal by getting out of the selection "state".

**Comment by nimble0** [comment]
Fixed in 08de096b649a78eb1a028b721fb097a9f653b4b1
