### ISSUE TITLE
Where's the "submit" button?

### ISSUE THREAD

**Issue by user202729** [nimble0/dotterel#5]
Other keyboard have a "go" or "submit" button. On Dotterel, R-R does not work (although it does insert a newline for multiline textboxes)

**Comment by nimble0** [comment]
No support for those kind of actions currently. I do find that R-R usually works.

I could add these as commands but I'm also considering changing the keyboard commands to perform these actions (#Return -> go, #Tab -> next field, etc.).

**Comment by nimble0** [comment]
Added in https://github.com/nimble0/dotterel/commit/becdadaa5ca02dd580de9890c6b4d5ebeab6ed3c it'll be available in the next release as the command `{IME:EDITOR_ACTION}`.

Only one action ever seems to be possible at a time so there's only one command. I don't think it's worth introducing special behavior for a single command so I won't be mapping {#Return} to it.
